Add term relationship type model
MauroDataMapper/mdm-resources pull request #32
Opened 2021-09-13 11:44 UTC by atpw25

2021-09-14 09:19 UTC, pjmonks requested changes
Could you look over the comments I made please? Also, this PR is missing the build output - currently we have to commit the output from `npm run build` as well.

2021-09-14 09:19 UTC, pjmonks commented on src/mdm-term-relationship-type.model.ts
> +export type TermRelationshipTypeIndexResponse = MdmIndexResponse<TermRelationshipType & Navigatable>;
If `breadcrumbs` is returned from both the index and `GET` endpoints, shouldn't `Navigatable` just be an extension of `TermRelationType`?

```ts
export interface TermRelationshipType extends Navigatable {
}
```

2021-09-14 09:19 UTC, pjmonks commented on src/mdm-term-relationship-type.model.ts
> +  domainType: TermRelationshipTypeType;
Two things here:

1. `domainType` feels like it should be of type `CatalogueItemDomainType`, meaning `TermRelationshipType` should be added to that enum
2. Then you can extend `TermRelationshipType` with the `CatalogueItem` interface.

2021-09-15 19:05 UTC, atpw25 commented
Updated. Also included build output.

2021-09-16 08:20 UTC, pjmonks approved these changes
All changes are good, thanks. I will merge once Jenkins allows it.

2021-09-16 08:23 UTC, merged